receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  transform:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["level"], "foo")
          - set(attributes["level"], "baz")

exporters:
  otlphttp/logs:
    # change this depending on where you're running loki (can be made configurable)
    endpoint: http://host.docker.internal:3100/otlp
    tls:
      insecure: true
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch, transform]
      exporters: [otlphttp/logs, debug]
