name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Restore npm cache
        id: restore-npm-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/yarn.lock', '!node_modules/**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Save npm cache
        id: save-npm-cache
        if: steps.restore-npm-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
          key: ${{ steps.restore-npm-cache.outputs.cache-primary-key }}
      - name: Build plugin
        run: npm run build
      - name: Compatibility check
        run: npx @grafana/levitate@latest is-compatible --path src/module.tsx --target @grafana/data,@grafana/ui,@grafana/runtime
